---
sudo: false
language: rust
rust:
  - nightly

os:
  - linux
  - osx

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - gcc -shared -o libnya.dylib -fPIC -Iinclude $(python-config --cflags) $(python-config --ldflags) src/lib.c
  - make
