---
sudo: true
language: rust
rust:
  - nightly

os:
  - osx

env:
  - ARCH=x86_64
  - ARCH=i686

install:
  - mkdir -p /tmp/ghc
  - tar zx -C /tmp/ghc < <(curl -sSfL http://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-x86_64-apple-darwin.tar.xz)
  - cd /tmp/ghc/ghc-8.0.1
  - ./configure
  - sudo make install
  - cd -

script:
  - ghc -o libadder.dylib -shared -static -fPIC Adder.hs StartEnd.c -lHSrts -lCffi
  - gcc -shared -o libss.so -fPIC libss.c libadder.dylib -I"$(ghc --print-libdir)/include"
  - install_name_tool -change "@rpath/libadder.dylib" "@executable_path/libadder.dylib" libss.so
  - gcc -o main main.c
  - ./main
