[package]
name = "libnya"
version = "0.1.0"
authors = [
    "adjivas <adjivas@users.noreply.github.com>",
]
repository = "https://github.com/Arukana/libnya.git"
readme = "README.md"
keywords = ["nya"]
license = "GPL-3.0"

[dependencies.libc]
version = "0.2"
default-features = false
